// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PopRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopRequest) Reset()         { *m = PopRequest{} }
func (m *PopRequest) String() string { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()    {}
func (*PopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_de2f237477d39dce, []int{0}
}
func (m *PopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopRequest.Unmarshal(m, b)
}
func (m *PopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopRequest.Marshal(b, m, deterministic)
}
func (dst *PopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopRequest.Merge(dst, src)
}
func (m *PopRequest) XXX_Size() int {
	return xxx_messageInfo_PopRequest.Size(m)
}
func (m *PopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopRequest proto.InternalMessageInfo

func (m *PopRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Data struct {
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Topic                string   `protobuf:"bytes,7,opt,name=topic,proto3" json:"topic,omitempty"`
	Delay                int32    `protobuf:"varint,8,opt,name=delay,proto3" json:"delay,omitempty"`
	Ttr                  int32    `protobuf:"varint,9,opt,name=ttr,proto3" json:"ttr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_de2f237477d39dce, []int{1}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Data) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Data) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Data) GetDelay() int32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *Data) GetTtr() int32 {
	if m != nil {
		return m.Ttr
	}
	return 0
}

type DataResponse struct {
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *Data    `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_de2f237477d39dce, []int{2}
}
func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (dst *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(dst, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PopRequest)(nil), "grpc.PopRequest")
	proto.RegisterType((*Data)(nil), "grpc.Data")
	proto.RegisterType((*DataResponse)(nil), "grpc.DataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DelayQueueClient is the client API for DelayQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DelayQueueClient interface {
	Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type delayQueueClient struct {
	cc *grpc.ClientConn
}

func NewDelayQueueClient(cc *grpc.ClientConn) DelayQueueClient {
	return &delayQueueClient{cc}
}

func (c *delayQueueClient) Pop(ctx context.Context, in *PopRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/grpc.DelayQueue/Pop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelayQueueServer is the server API for DelayQueue service.
type DelayQueueServer interface {
	Pop(context.Context, *PopRequest) (*DataResponse, error)
}

func RegisterDelayQueueServer(s *grpc.Server, srv DelayQueueServer) {
	s.RegisterService(&_DelayQueue_serviceDesc, srv)
}

func _DelayQueue_Pop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelayQueueServer).Pop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DelayQueue/Pop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelayQueueServer).Pop(ctx, req.(*PopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DelayQueue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DelayQueue",
	HandlerType: (*DelayQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pop",
			Handler:    _DelayQueue_Pop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_de2f237477d39dce) }

var fileDescriptor_server_de2f237477d39dce = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0xe2, 0xb4, 0xf4, 0xa8, 0x50, 0x75, 0x62, 0x38, 0x31, 0xa0, 0xc8, 0x53, 0x16,
	0x32, 0x94, 0x91, 0xb5, 0x3f, 0xa0, 0x64, 0x66, 0x71, 0xe3, 0x53, 0x89, 0x04, 0xd8, 0xd8, 0x0e,
	0x52, 0xff, 0x3d, 0xf2, 0x85, 0xaa, 0xdd, 0xde, 0x7b, 0x3e, 0xbf, 0xcf, 0x3e, 0x58, 0x47, 0x0e,
	0xbf, 0x1c, 0x3a, 0x1f, 0x5c, 0x72, 0xa8, 0x8e, 0xc1, 0x0f, 0x5a, 0x03, 0xec, 0x9d, 0xef, 0xf9,
	0x67, 0xe2, 0x98, 0xf0, 0x01, 0xea, 0xe4, 0xfc, 0x38, 0x50, 0xd1, 0x14, 0xed, 0xaa, 0x9f, 0x8d,
	0xfe, 0x00, 0xb5, 0x33, 0xc9, 0xe0, 0x3d, 0x94, 0xa3, 0xa5, 0x52, 0x8e, 0xca, 0xd1, 0x22, 0x82,
	0x3a, 0x38, 0x7b, 0xa2, 0x4a, 0x12, 0xd1, 0x97, 0x86, 0xe5, 0x55, 0x43, 0x4e, 0x2d, 0x7f, 0x9a,
	0x13, 0xdd, 0x36, 0x45, 0x5b, 0xf7, 0xb3, 0xc1, 0x0d, 0x54, 0x29, 0x05, 0x5a, 0x49, 0x96, 0xa5,
	0x7e, 0x87, 0x75, 0x26, 0xf5, 0x1c, 0xbd, 0xfb, 0x8e, 0x9c, 0x09, 0x83, 0xb3, 0x4c, 0x4a, 0x46,
	0x44, 0x23, 0xc1, 0xf2, 0x8b, 0x63, 0x34, 0x47, 0xa6, 0x5a, 0x18, 0x67, 0x8b, 0x4f, 0xa0, 0xac,
	0x49, 0x86, 0x16, 0x4d, 0xd1, 0xde, 0x6d, 0xa1, 0xcb, 0x1f, 0xec, 0xa4, 0x4f, 0xf2, 0xed, 0x2b,
	0xc0, 0x2e, 0x83, 0xdf, 0x26, 0x9e, 0x18, 0x9f, 0xa1, 0xda, 0x3b, 0x8f, 0x9b, 0x79, 0xec, 0xb2,
	0x84, 0x47, 0xbc, 0xba, 0xf8, 0xff, 0x10, 0x7d, 0x73, 0x58, 0xc8, 0xd6, 0x5e, 0xfe, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x57, 0x1a, 0x40, 0x14, 0x45, 0x01, 0x00, 0x00,
}
